steps:
  # Generate image tag
  - name: ubuntu
    id: generate-image-tag
    entrypoint: bash
    args:
    - '-c'
    - echo $(date) | md5sum | awk '{print $1}' > tag.txt
    - cat tag.txt

  # Example: how to use gsutil commands
  - name: 'gcr.io/cloud-builders/gsutil'
    id: list_buckets_in_project
    args: ['ls']

  # Example: how to use gcloud commands
  - name: 'gcr.io/cloud-builders/gcloud'
    id: list_cloud_functions
    args: ['functions', 'list', '--regions=us-west2']

timeout: 1200s

substitutions:
  _GCR_REGION: us
  _ENV: sample
