steps:
  - name: ubuntu
    id: generate-image-tag
    entrypoint: bash
    args:
    - '-c'
    - echo $(date) | md5sum | awk '{print $1}' > tag.txt

  - name: gcr.io/cloud-builders/docker
    id: docker-build-push-custom
    entrypoint: bash
    args:
    - '-c'
    - |
      tag=`cat tag.txt`
      docker build -t "gcr.io/$PROJECT_ID/$BRANCH_NAME:$tag" .
      docker push "gcr.io/$PROJECT_ID/$BRANCH_NAME:$tag"

  # build an artifact using the docker builder
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--build-arg",
        "NODE_ENV=develop",
        "-t",
        "${_GCR_REGION}.gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA",
        ".",
      ]

  # push image to GCR repository
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_GCR_REGION}.gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA"]

substitutions:
  _GCR_REGION: us
