steps:
  # Generate image tag
  - name: ubuntu
    id: generate-image-tag
    entrypoint: bash
    args:
    - '-c'
    - echo $(date) | md5sum | awk '{print $1}' > tag.txt

  # Docker build & push - option 1
  - name: gcr.io/cloud-builders/docker
    id: docker-build-push-custom
    entrypoint: bash
    args:
    - '-c'
    - |
      tag=`cat tag.txt`
      docker build -t "gcr.io/$PROJECT_ID/$BRANCH_NAME:$tag" .
      docker push "gcr.io/$PROJECT_ID/$BRANCH_NAME:$tag"

  # Docker build - option 2
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--build-arg",
        "ENV=${_ENV}",
        "-t",
        "${_GCR_REGION}.gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA",
        ".",
      ]

  # Push image to GCR repository
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_GCR_REGION}.gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA"]

  # Example: how to use gsutil commands
  - name: 'gcr.io/cloud-builders/gsutil'
    id: list_buckets_in_project
    args: ['ls']

  # Example: how to use gcloud commands
  - name: 'gcr.io/cloud-builders/gcloud'
    id: list_cloud_functions
    args: ['functions', 'list', '--regions=us-west2']

timeout: 1200s

substitutions:
  _GCR_REGION: us
  _ENV: develop
